### PR TITLE
Notebook

### PR DESCRIPTION
**Pull request by GbotemiB**

### CODE REVIEW

**Comment by jessLryan** [comment]
We should keep the files in the repo as .py files - can you please re-upload as .py?
We should also ideally remove any references to local files - for now we can just have n1 and n2 as user inputs, which will be local network files for now

**Comment by GbotemiB** [comment]
The notebook is just a means to run the script interactively for now. I think we can leave it for now, just for iterations.

Regarding references, Can you clarify a bit more?

**Comment by jessLryan** [comment]
I'd like to keep the file as a .py file
r.e. local files, I mean that there should not be any strings in the file containing the string "/Users/gbotemi/....."

**Comment by GbotemiB** [comment]
Regarding the local files, I don't have my full file path appended to the files.

I think you are referring to the results of the runs in the notebook.

**Comment by GbotemiB** [comment]
Hello @jessLryan, 

If I may ask, is there any reason you would like to have only `.py` files?

I strongly advise using a notebook for experimentation.

**Comment by jessLryan** [comment]
We've had the notebook vs .py file debate in the discord chat - see the response by @ekatef

**Comment by GbotemiB** [comment]
Thanks @jessLryan. I have seen the conversation in the discussion.

**Pull request closed without merging**
